#!/usr/bin/env bash
# ============================================================
# K-9 SETUP WIZARD — Interactive .env configurator
# Run AFTER k9-install.sh to configure API keys and secrets
#
# Usage: ./k9-setup-wizard.sh
# ============================================================

set -euo pipefail

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

K9_HOME="${K9_HOME:-$HOME/k9}"
ENV_FILE="${K9_ENV_FILE:-$K9_HOME/k9-llm-router/.env}"

echo -e "${BOLD}${CYAN}"
echo "  ════════════════════════════════════════════════════════════"
echo "    K-9 ECOSYSTEM — SETUP WIZARD"
echo "    Interactive .env configuration"
echo "  ════════════════════════════════════════════════════════════"
echo -e "${NC}"

if [ ! -f "$ENV_FILE" ]; then
  echo -e "${RED}Error: .env not found at $ENV_FILE${NC}"
  echo "Run k9-install.sh first."
  exit 1
fi

ask() {
  local prompt="$1"
  local varname="$2"
  local hint="${3:-}"
  local current="${!varname:-}"
  local display=""
  [ -n "$current" ] && display=" [current: ${current:0:8}...]"
  [ -n "$hint" ] && display="$display\n  hint: $hint"
  
  echo -e "${CYAN}$prompt${NC}$display"
  read -rp "  → " input
  if [ -n "$input" ]; then
    eval "$varname='$input'"
  fi
}

# Load current values
if [ -f "$ENV_FILE" ]; then
  while IFS='=' read -r key val; do
    [[ "$key" =~ ^# ]] && continue
    [ -z "$key" ] && continue
    eval "$key='$val'" 2>/dev/null || true
  done < "$ENV_FILE"
fi

echo -e "${BOLD}Step 1: AI / LLM Keys${NC}\n"
ask "Gemini API Key" GEMINI_API_KEY "https://aistudio.google.com/apikey"
ask "Anthropic API Key (optional)" ANTHROPIC_API_KEY "Claude — leave blank for local Ollama"
ask "OpenAI API Key (optional)" OPENAI_API_KEY "GPT — leave blank for local Ollama"

echo -e "\n${BOLD}Step 2: Supabase / Orbitron${NC}\n"
ask "Supabase URL" SUPABASE_URL "Already set: https://ziqenqqgnqxqrazmjohs.supabase.co"
ask "Supabase Anon Key" SUPABASE_ANON_KEY "Supabase dashboard → Settings → API"
ask "Orbitron Integration Key" AEG_INTEGRATION_KEY "from api_configurations table in Supabase"

echo -e "\n${BOLD}Step 3: AEG / On-Chain${NC}\n"
ask "AEG Node ID (wallet address)" AEG_NODE_ID "your Base L2 wallet address"
ask "Deployer Private Key (AEG contracts)" DEPLOYER_PK "0x... — never share this"
ask "Owner Address" OWNER_ADDRESS "0x... — your EOA or multisig"
ask "Basescan API Key (optional)" BASESCAN_API_KEY "https://basescan.org — for contract verification"

echo -e "\n${BOLD}Step 4: Contract Addresses (from AEG-4/AEG-6 deploy)${NC}\n"
ask "AEG Treasury Address" AEG_TREASURY_ADDRESS "0x11416f3B83096D38E79a1BdA9e15c21edE8932D4"
ask "AEG Governor Address" AEG_GOVERNOR_ADDRESS "0x096cdCf288EAB57025c3c18eaa8b0e1f9987A4D4"
ask "Session Wallet Address" SESSION_WALLET_ADDRESS "0x25e2CFC6A3ed9733a632b630953c6931113E8148"
ask "Verifier Address" VERIFIER_ADDRESS "0x8b62Da4c17ff1B55Be033d1847648c490BA0b82D"

echo -e "\n${BOLD}Step 5: Optional Services${NC}\n"
ask "Cohere API Key (reranking)" COHERE_API_KEY "optional — for hybrid RAG reranking"
ask "Redis URL" REDIS_URL "default: redis://localhost:6379"
ask "Browserbase API Key" BROWSERBASE_API_KEY "optional — for browser automation"

# Write .env
echo -e "\n${CYAN}Writing $ENV_FILE...${NC}"

cat > "$ENV_FILE" << ENVEOF
# K-9 Ecosystem — Generated by k9-setup-wizard.sh
# $(date)

# ── AI / LLM ────────────────────────────────────────────────
GEMINI_API_KEY=${GEMINI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}

# ── Supabase / Orbitron ─────────────────────────────────────
SUPABASE_URL=${SUPABASE_URL:-https://ziqenqqgnqxqrazmjohs.supabase.co}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-}
ORBITRON_WEBHOOK_URL=${ORBITRON_WEBHOOK_URL:-}
ORBITRON_WEBHOOK_SECRET=${ORBITRON_WEBHOOK_SECRET:-}

# ── AEG ─────────────────────────────────────────────────────
AEG_INTEGRATION_KEY=${AEG_INTEGRATION_KEY:-}
AEG_NODE_ID=${AEG_NODE_ID:-}
AEG_OPERATOR_KEY=${AEG_OPERATOR_KEY:-dev}

# ── On-Chain / Foundry ──────────────────────────────────────
DEPLOYER_PK=${DEPLOYER_PK:-}
OWNER_ADDRESS=${OWNER_ADDRESS:-}
BASE_SEPOLIA_RPC=${BASE_SEPOLIA_RPC:-https://sepolia.base.org}
BASE_MAINNET_RPC=${BASE_MAINNET_RPC:-https://mainnet.base.org}
BASESCAN_API_KEY=${BASESCAN_API_KEY:-}

# ── Contract Addresses (Base Sepolia) ─────────────────────
AEG_TREASURY_ADDRESS=${AEG_TREASURY_ADDRESS:-0x11416f3B83096D38E79a1BdA9e15c21edE8932D4}
AEG_GOVERNOR_ADDRESS=${AEG_GOVERNOR_ADDRESS:-0x096cdCf288EAB57025c3c18eaa8b0e1f9987A4D4}
SESSION_WALLET_ADDRESS=${SESSION_WALLET_ADDRESS:-0x25e2CFC6A3ed9733a632b630953c6931113E8148}
VERIFIER_ADDRESS=${VERIFIER_ADDRESS:-0x8b62Da4c17ff1B55Be033d1847648c490BA0b82D}

# ── K-9 Runtime ─────────────────────────────────────────────
K9_HOME=${K9_HOME}
K9_WALLPAPER=${K9_WALLPAPER_DIR:-$HOME/.local/share/k9-wallpaper}
K9_JEPA_ENDPOINT=http://localhost:8765/route
CIRCUITS_DIR=./contracts/aeg9_circuit
PROOFS_DIR=./proofs

# ── CB-2 Semantic Cache ─────────────────────────────────────
REDIS_URL=${REDIS_URL:-redis://localhost:6379}
COHERE_API_KEY=${COHERE_API_KEY:-}

# ── Guardrails ──────────────────────────────────────────────
GUARDRAILS_ENABLED=true
GUARDRAILS_BLOCK_PII=true
GUARDRAILS_TOX_THRESH=0.7

# ── Browser Automation ──────────────────────────────────────
BROWSERBASE_API_KEY=${BROWSERBASE_API_KEY:-}
ENVEOF

echo -e "${GREEN}✅ .env written to $ENV_FILE${NC}"
echo ""
echo -e "${YELLOW}Review and edit manually if needed:${NC} nano $ENV_FILE"
echo ""
echo -e "${BOLD}Next:${NC} cd $K9_HOME/k9-llm-router && ./launch-economic-stack.sh start"
